name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Build plugin
        run: ./gradlew build --no-daemon -PhorreoUsername=${{ secrets.PUBLISH_USERNAME }} -PhorreoPassword=${{ secrets.PUBLISH_PASSWORD }}

      - name: Upload plugin jars
        uses: actions/upload-artifact@v3
        with:
          name: LaunchPlates-Artifacts
          path: build/libs/LaunchPlates-*
          if-no-files-found: error

      - name: Publish to package registry
        run: ./gradlew publish --no-daemon -PhorreoUsername=${{ secrets.PUBLISH_USERNAME }} -PhorreoPassword=${{ secrets.PUBLISH_PASSWORD }}
